import type { Config } from '../../src/shared/types.js';

export function createConfig(overrides: Partial<Config> = {}): Config {
  return {
    discordBotToken: 'discord-token',
    discordChannelId: 'channel-1',
    ownerIds: ['owner-1'],
    discordBossId: 'owner-1',
    allowedChannelIds: ['channel-1', 'reporting'],
    allowedUserIds: ['owner-1'],
    allowedAgentIds: [],
    daemonApiToken: 'daemon-token',
    peerAgentId: 'peer-agent',
    reportingChannelId: 'reporting',
    discordPrefix: '!',
    discordResetCmd: '!reset',
    daemonPort: 18790,
    geminiPath: 'gemini',
    geminiModel: 'gemini-3.1-flash-lite-preview',
    geminiTimeoutMs: 300000,
    geminiMaxConcurrent: 3,
    conversationHistoryLength: 30,
    promptHistoryMessageLimit: 12,
    promptHistoryCharBudget: 6000,
    streaming: true,
    queueMaxDepth: 20,
    enableDMs: true,
    requireMention: false,
    respondToReplies: true,
    memoryScope: 'channel',
    autoStartDaemon: true,
    useGeminiCliSessions: true,
    geminiSessionBindingScope: 'channel',
    cliIdleTimeoutMs: 300000,
    autonomous: {
      enabled: false,
      intervalMs: 300000,
      targetChannelId: 'reporting',
      targetChannelName: '',
      assumeMasterAway: true,
      fourChan: {
        enabled: false,
        board: 'a',
        keywords: ['one piece'],
        minSignal: 3,
        cooldownMs: 3600000,
        signalWindowMs: 1800000,
        timelineLimit: 200,
      },
    },
    ...overrides,
  };
}
