import type { Config } from '../../src/shared/types.js';

export function createConfig(overrides: Partial<Config> = {}): Config {
  return {
    discordBotToken: 'test-token',
    discordChannelId: 'channel-1',
    discordServerId: '',
    discordServerName: '',
    ownerIds: ['owner-1'],
    discordAdminId: 'owner-1',
    allowedChannelIds: ['channel-1', 'channel-2'],
    allowedUserIds: ['owner-1'],
    allowedAgentIds: [],
    daemonApiToken: 'daemon-token',
    discordPrefix: '!',
    discordResetCmd: '!reset',
    daemonPort: 18790,
    geminiPath: 'gemini',
    geminiModel: 'gemini-3.1-flash-lite-preview',
    geminiTimeoutMs: 300000,
    geminiMaxConcurrent: 3,
    conversationHistoryLength: 30,
    promptHistoryMessageLimit: 12,
    promptHistoryCharBudget: 6000,
    streaming: true,
    queueMaxDepth: 20,
    enableDMs: true,
    requireMention: false,
    respondToReplies: true,
    memoryScope: 'global',
    autoStartDaemon: true,
    useGeminiCliSessions: true,
    geminiSessionBindingScope: 'global',
    cliIdleTimeoutMs: 300000,
    ...overrides,
  };
}
